### ISSUE TITLE
アップロード api の実装

### ISSUE THREAD

**Issue by earlgray283** [szpp-dev-team/cvpn#5]
# 要件
```command
$ cvpn upload {ソース} {アップロード先の URL}
```
アップロードできるようにして欲しい。
進捗はできればで良いから、せめてアップロードが完了したことだけは出力して欲しい。

# api 情報
なんも調べてないから調べるところから始めて欲しい。
```console
Request URL(example): 不明
Method: 多分 POST じゃないかな？
header: cookie だけでいいと思う
```

# できればリスト
+ プログレスバーを表示できるとそれっぽくて良い
+ 複数アップロード

**Comment by earlgray283** [comment]
これは api を調べないといけないところが大変。単純であれば良いけど・・。

**Comment by arumakan1727** [comment]
## ファイルアップロード API 情報

```
Request URL: /dana/fb/smb/wfb.cgi
Method: POST
Header: 多分Cookieだけ
```

リクエストボディパラメータ (`キー` : `値` の形式で表示。`値` はあくまでも例。値が無のやつは多分無でOK)
```
xsauth: 65bf270a09fbe3hoge7a4027d
txtServerUploadID: 

file1
txtRenameFile1
chkUnzip1

...(略)...

file5 
txtRenameFile5
chkUnzip5

t: p
v: resource_18807999999999999.176066.2,2020 (多分ボリュームのID (FS, FS Share とか))
si:
ri:
pi:
dir: student\hogehoge (ディレクトリパス)
acttype: upload
confirm: yes
trackid: 65bf270a09fhoge728b9f7a4hoged9
ignoreDfs: 1
```

## 備考, 懸念
- ファイルを実際にアップロードしたときのリクエスト内容をWebブラウザの開発者ツールで見ようとしたが、アップロード時に新しいウィンドウが開いてしまうためリクエスト内容を見れなかった (試せば分かる)。
- ということでアップロードフォーム画面の `<form id="frmUpload_4" ...>` 内の `name="xxxxx"` の xxxx を全て抽出してここに載せた。

- `xsauth` はアップロードフォーム画面に `<input type="hidden">` で埋め込まれていたので、まずアップロードフォーム画面へリクエストを飛ばしてレスポンス内から `xsauth` の値を抽出する必要がありそう (`trackid` とかも)

**Comment by earlgray283** [comment]
これえぐいので先に実装進めることにします。

**Comment by earlgray283** [comment]
`xsauth` の値はログイン時に生成されるっぽいから、ログイン api の方で格納するようにしておくね

**Comment by earlgray283** [comment]
`trackid` は `escape("7411e349673c68925a8cd8664cc18437" + (new Date().getTime()))`

**Comment by earlgray283** [comment]
trackid は `escape("32桁の乱数" + (new Date().getTime()))` かな？

**Comment by earlgray283** [comment]
trackid はファイルアップロード画面を開く度に変わるから、アップロードコマンドが実行される度に取得する

**Comment by arumakan1727** [comment]
# ファイルアップロードAPI

## アップロード手順
ファイルのアップロードは3つのステップを踏む必要がある。

1. アップロード先を定める。

    FS上に存在する個々のディレクトリは、①ボリューム(ドライブ？) と ②ディレクトリ の2つのパラメータで決まる。
    ボリュームは `v`, ディレクトリは `dir` というキー名で、URLのクエリパラメータやPOSTリクエストボディの中に見つけられる。

2. `trackid` を得る (数字とアルファベットの羅列)。

    *適切なリクエストを飛ばす* と ファイルアップロード用のフォームのHTMLが返ってくる。
    HTML中の `<input type="hidden" id="trackid_1" name="trackid" value="xxxxxxxxxxx">` の `value` をスクレイピングで抜き出す。
    (idが`trackid_1`なのでセレクタを `#trackid_1` にすれば簡単に抽出できる)

    *適切なリクエストを飛ばす* というのは、Webブラウザで 「ファイルのアップロード」 ボタンを押してファイル選択画面を表示するリクエストと同じ (APIの詳細は後述)。

3. ファイルをアップロードする。

    2 で得た `trackid` をリクエストに含めながら、Content-Type は multipart で送信する。

## アップロード前段階API (`trackid` 取得用)

```
[POST] /dana/fb/smb/wu.cgi

URL Parameter
=============
    -None-

Request Body
============
    acttype:    "upload"
    ignoreDfs:  "1"
    xsauth:     "{{xsauth}}"
    t:          "p"
    v:          "{{volumeID}}"
    dir:        "{{dir}}"
    si:         ""
    ri:         ""
    pi:         ""

Response
========
    成功時
    StatusCode: 200
    Content-Type: text/html
```

## アップロードAPI
```
[POST] /dana/fb/smb/wu.cgi?trackid={{trackid_with_unix_time}}

URL Parameter
=============
    trackid_with_unix_time:
        `trackid` の末尾にUnix時間を追加した文字列。
        ブラウザでファイル選択画面のHTMLのソースを見ると、JS の OpenStatus() 関数内で
        trackid に new Date().getTime() を追加していることが分かる。
        

Request Body (Content-Type は multipart)
============
    acttype:            "upload"
    confirm:            "yes"
    ignoreDfs:          "1"
    trackid:            "{{trackid}}"
    txtRenameFile1:     "{{txtRenameFile1}}
    txtServerUploadID:  ""
    xsauth:             "{{xsauth}}"
    t:                  "p"
    v:                  "{{volumeID}}"
    dir:                "{{dir}}"
    si:                 ""
    ri:                 ""
    pi:                 ""
    file1:              "{{file1_content}}"
    
    file1〜file5まであるが、リクエストボディに含めなくてもアップロードできたのでfile2以降は指定しない。

Response
========
    成功時
    StatusCode: 200
    Content-Type: text/html
```

**Comment by earlgray283** [comment]
trackid って unix_time も含めたものだったのか・・・

**Comment by earlgray283** [comment]
アップロードが、できない

**Comment by earlgray283** [comment]
あとコマンドラインもパースも未完成であることを失念していたので再オープン
